# Generated by Django 5.1.2 on 2024-10-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("senha", models.CharField(max_length=100)),
                ("nascimento", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
