# Generated by Django 5.1.3 on 2024-11-08 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard_prof', '0002_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=10)),
                ('semestre', models.CharField(max_length=20)),
                ('curso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('pontos', models.IntegerField()),
                ('porcentagem', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nivel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DesempenhoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.IntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_prof.aluno')),
                ('pilar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_prof.pilar')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='desempenho',
            field=models.ManyToManyField(through='dashboard_prof.DesempenhoAluno', to='dashboard_prof.pilar'),
        ),
    ]
