# Generated by Django 5.1.3 on 2024-11-06 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_aluno', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
